apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: alpaca-python
  janus-idp.io/tekton: alpaca-python
  backstage.io/kubernetes-id: alpaca-python
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: alpaca-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
